### PR TITLE
Introduce error message system

### PR DESCRIPTION
**Pull request by dbrgn**
@schmijos or @netzhuffle, want to take a look at some JS / Angular code?

### CODE REVIEW

**Comment by dbrgn** [comment]
This fixes #2.

**Comment by netzhuffle** [comment]
Looks good!

**Comment by dbrgn** [comment]
Thanks @netzhuffle!

**Comment by schmijos** [comment]
:+1: but smaller commits would be nice.

**Comment by dbrgn** [comment]
My code isn't big, it's mostly libraries :)

**Pull request merged**
